
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then(function () {
      // Inserts seed entries
      return knex('users').insert([
        {email: 'garyskalinsky@yahoo.com', username: 'garyskalinsky', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'Gary', lname: 'Skalinsky', bio: 'Seeking Adventure', age: 24, zipcode: '95011', img_url:"https://s3-eu-west-1.amazonaws.com/video.gallereplay.com/production/user_74/picture_17112016100959.jpg", seeking:"female", gender:"male"},
        {email: 'joshgabanna@yahoo.com', username: 'joshgabanna', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'Josh', lname: 'Gabanna', bio: "Really looking for that key component in my", age: 21, zipcode: '95012', img_url:"https://rudranibanikmd.com/wp-content/uploads/2017/02/44813671_m.jpg", seeking:"female", gender:"male"},
        {email: 'lucasromero@yahoo.com', username: 'lucasromero', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'Lucas', lname: 'Romero', bio: "Where the ladies at", age: 20, zipcode: '95013', img_url:"https://i.pinimg.com/originals/81/c1/f3/81c1f355bdf8bcd6dbb57beabef2cf98.jpg", seeking:"female", gender:"male"},
        {email: 'marcusames@yahoo.com', username: 'marcusames', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'Marcus', lname: 'Ames', bio: "Never forget to git pull ladies!", age: 18, zipcode: '95014', img_url:"https://pbs.twimg.com/profile_images/501861077194665985/zZlv3UqF_400x400.jpeg", seeking:"female", gender:"male"},
        {email: 'samurcuyo@yahoo.com', username: 'samurcuyo', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'Sam', lname: 'Urcuyo', bio: "What's up i'm Sam!", age: 30, zipcode: '95015', img_url:"https://www.ninjaonlinedating.com/images/Articles/Good_Dating_Profile_Photo.jpg", seeking:"female", gender:"male"},
        {email: 'samanthajones@yahoo.com', username: 'samanthajones', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'Samantha', lname: 'Jones', bio: 'It is my first time using this application!', age: 25, zipcode: '95016', img_url:"https://cdn.techgyd.com/100-Cute-Images-of-Girls-Pets-Babies-15.jpg", seeking:"male", gender:"female"},
        {email: 'jessicabrewer@yahoo.com', username: 'jessicabrewer', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'Jessica', lname: 'Brewer', bio: 'This is my favorite application!', age: 29, zipcode: '95017', img_url:"https://www.abc.net.au/news/image/8450366-3x4-700x933.jpg", seeking:"male", gender:"female"},
        {email: 'laurabaxter@yahoo.com', username: 'laurabaxter', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'Laura', lname: 'Baxter', bio: 'Hello i am Laura!', age: 31, zipcode: '95018', img_url:"http://www.lacartes.com/images/business/169868/471628/l/642010.jpg", seeking:"male", gender:"female"},
        {email: 'lucymsmith@yahoo.com', username: 'lucysmith', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'Lucy', lname: 'Smith', bio: 'Hello i am Lucy!', age: 27, zipcode: '95019', img_url:"https://cdn3.foap.com/images/720f60a8-8442-45ad-8f49-c93fb1033ec2/w640.jpg?1496518064", seeking:"male", gender:"female"},
        {email: 'monicaking@yahoo.com', username: 'monicaking', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'Monica', lname: 'King', bio: 'Hello i am Monica!', age: 22, zipcode: '96001', img_url:"https://www.tricksclub.com/wp-content/uploads/2018/10/Awesome-Pic-For-Girl.png", seeking:"male", gender:"female"},
        {email: 'ryanjewel@yahoo.com', username: 'ryanjewel', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'Ryan', lname: 'Jewel', bio: "What's up im Ryan!", age: 30, zipcode: '96002', img_url:"http://blog.chemistry.com/wp-content/uploads/2012/09/man-smiling.jpg", seeking:"female", gender:"male"},
        {email: 'skylaradams@yahoo.com', username: 'skylaradams', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'Skylar', lname: 'Adams', bio: "Hello there! I'm Skylar!", age: 23, zipcode: '96003', img_url:"https://www.mills.edu/uniquely-mills/students-faculty/student-profiles/images/student-profile-gabriela-mills-college.jpg", seeking:"male", gender:"female"},
        {email: 'johnownes@yahoo.com', username: 'johnownes', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'John', lname: 'Owens', bio: "What's up guys im John!", age: 28, zipcode: '96004', img_url:"https://images.unsplash.com/photo-1505503693641-1926193e8d57?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=22e1d8d5234640647a521b665a04c050&dpr=1&auto=format&fit=crop&w=1000&q=80&cs=tinysrgb", seeking:"female", gender:"male"},
        {email: 'ashleyevans@yahoo.com', username: 'ashleyevans', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'Ashley', lname: 'Evans', bio: "Looking for that key component!", age: 24, zipcode: '96005', img_url:"https://image.freepik.com/free-photo/portrait-of-a-happy-woman-smiling_1303-9953.jpg", seeking:"male", gender:"female"},
        {email: 'mannysanders@yahoo.com', username: 'mannysanders', password: '$2a$10$16HA89xoCCWDZ.Kfjes6vepMaZKYZ106z/b5CTXVnxtO/l8DvEMyi', fname: 'Manny', lname: 'Sanders', bio: "You know what it is!!", age: 26, zipcode: '96006', img_url:"http://www.mardoman.net/wp-content/uploads/2008/05/91.jpeg", seeking:"female", gender:"male"}
      ]);
    });
};
